## CST2109 - Lab 7 - Classification Algorithms

### 1. Perform EDA on the Titanic Dataset

In [40]:
import pandas as pd

df = pd.read_csv("titanic.csv")
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [41]:
print("Ngan Nguyen - 041154207")
df.shape

Ngan Nguyen - 041154207

(891, 12)

In [42]:
print("Ngan Nguyen - 041154207")
df.info()

Ngan Nguyen - 041154207
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [43]:
print("Ngan Nguyen - 041154207")
df.columns

Ngan Nguyen - 041154207

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [44]:
print("Ngan Nguyen - 041154207")
df.describe()

Ngan Nguyen - 041154207

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [45]:
print("Ngan Nguyen - 041154207")
df.isnull().sum()

Ngan Nguyen - 041154207

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

### 2. Answer the following questions:
a.	Number of instances?

In [46]:
print("Ngan Nguyen - 041154207")

print("Number of instances: ",df.shape[0])

Ngan Nguyen - 041154207
Number of instances:  891

b.	Number of attributes?

In [47]:
print("Ngan Nguyen - 041154207")

print("Number of attributes: ",df.shape[1])

Ngan Nguyen - 041154207
Number of attributes:  12

c.	How many missing values for each variable?

In [48]:
print("Ngan Nguyen - 041154207")
df.isnull().sum()

Ngan Nguyen - 041154207

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

d.	What is the target (Label) variable

In [49]:
print("Ngan Nguyen - 041154207")
print(f"\nTarget (Label) variable: 'Survived' (0 = No, 1 = Yes)")

Ngan Nguyen - 041154207

Target (Label) variable: 'Survived' (0 = No, 1 = Yes)

### 3. Perform Data Cleaning and Feature Engineering as needed.

In [50]:
print("Ngan Nguyen - 041154207")

# fill missing Age with median
df['Age'] = df['Age'].fillna(df['Age'].median())
print("Filled missing Age with median:", df['Age'].median())
 
# fill missing Embarked with mode
df['Embarked'] = df['Embarked'].fillna(df['Embarked'].mode()[0])
print("Filled missing Embarked with mode:", df['Embarked'].mode()[0])
 
# drop columns not useful for prediction
df.drop(columns=['Cabin', 'Name', 'Ticket', 'PassengerId'], inplace=True)
print("Dropped: Cabin (too many nulls), Name, Ticket, PassengerId")
 
# show non-numeric columns before conversion
print("\nNon-numeric columns:", list(df.select_dtypes(include='object').columns))

# use pd.get_dummies() to convert categories to numeric features
df = pd.get_dummies(df, columns=['Sex', 'Embarked'], drop_first=True)
 
print("\nColumns after conversion:", list(df.columns))
print("\nCleaned data preview:")
print(df.head())
print(f"\nMissing values after cleaning: {df.isnull().sum().sum()}")

Ngan Nguyen - 041154207
Filled missing Age with median: 28.0
Filled missing Embarked with mode: S
Dropped: Cabin (too many nulls), Name, Ticket, PassengerId

Non-numeric columns: ['Sex', 'Embarked']

Columns after conversion: ['Survived', 'Pclass', 'Age', 'SibSp', 'Parch', 'Fare', 'Sex_male', 'Embarked_Q', 'Embarked_S']

Cleaned data preview:
   Survived  Pclass   Age  SibSp  Parch     Fare  Sex_male  Embarked_Q  \
0         0       3  22.0      1      0   7.2500      True       False
1         1       1  38.0      1      0  71.2833     False       False
2         1       3  26.0      0      0   7.9250     False       False
3         1       1  35.0      1      0  53.1000     False       False
4         0       3  35.0      0      0   8.0500      True       False

   Embarked_S
0        True
1       False
2        True
3        True
4        True

Missing values after cleaning: 0

### 4. Apply Logistic regression, Decision Tree, and Random Forest Classification models.

In [55]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

#### Train Test Split

In [60]:
print("Ngan Nguyen - 041154207")

# Split target Survived and its features 
X = df.drop('Survived', axis=1)
y = df['Survived']
 
# 80:20 split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
print(f"Training size: {X_train.shape[0]}, Test size: {X_test.shape[0]}")

Ngan Nguyen - 041154207
Training size: 712, Test size: 179

#### Logistic Regression model:
Logistic Regression is trained using an iterative optimization algorithm
- The model does not find coefficients in one step
- It updates weights many times until it reaches the best solution.

Parameters (model hyperparameters):
- max_iter = maximum number of iterations allowed for training
- random_state: control randomness in data splitting or model training so that results are reproducible across multiple runs.

In [62]:
print("Ngan Nguyen - 041154207")

# Logistic Regression
lr = LogisticRegression(max_iter=1000, random_state=42)
lr.fit(X_train, y_train)
print(f"\nLogistic Regression Accuracy: {accuracy_score(y_test, lr.predict(X_test)):.4f}")

Ngan Nguyen - 041154207

Logistic Regression Accuracy: 0.8101

#### Desision Tree model:

* A Decision Tree is a supervised machine learning model that makes predictions by learning a series of if-else decision rules from the data.

* Key idea: Split data step-by-step based on feature conditions to reach a prediction.

Steps:
- Initialize model
- Fit → learn from training data
- Predict → test data
- Accuracy → evaluate performance

In [58]:
print("Ngan Nguyen - 041154207")

# Decision Tree
dt = DecisionTreeClassifier(random_state=42)
dt.fit(X_train, y_train)
print(f"Decision Tree Accuracy: {accuracy_score(y_test, dt.predict(X_test)):.4f}")

Ngan Nguyen - 041154207
Decision Tree Accuracy:       0.7821

#### Random Forest Classification model:

Logistic Regression is a supervised machine learning classification model used to predict the probability of a categorical outcome (usually binary) based on input features.

Key idea: It models the probability of class membership using a logistic (sigmoid) function. 
Predict probability → classify outcome

How prediction works:
- If probability ≥ 0.5 → class 1
- If probability < 0.5 → class 0

In [64]:
print("Ngan Nguyen - 041154207")

# Random Forest
rf = RandomForestClassifier(random_state=42)
rf.fit(X_train, y_train)
print(f"Random Forest Accuracy: {accuracy_score(y_test, rf.predict(X_test)):.4f}")

Ngan Nguyen - 041154207
Random Forest Accuracy: 0.8212

#### 5. Compute Confusion Matrix, Accuracy of each algorithm for the test set. Evaluate the performance of dataset with multiple Test / Train splits (80:20, 70:30, 85:15). Which one has the best performance.

In [74]:
print("Ngan Nguyen - 041154207")

from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

# Confusion Matrix (80:20 split)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
 
# Train and predict with each model
lr = LogisticRegression(max_iter=1000, random_state=42)
lr.fit(X_train, y_train)
lr_pred = lr.predict(X_test)
 
dt = DecisionTreeClassifier(random_state=42)
dt.fit(X_train, y_train)
dt_pred = dt.predict(X_test)
 
rf = RandomForestClassifier(random_state=42)
rf.fit(X_train, y_train)
rf_pred = rf.predict(X_test)
 
# Print confusion matrix and accuracy for each model
print("Logistic Regression (80:20)")
print("Confusion Matrix:")
print(confusion_matrix(y_test, lr_pred))
print("Accuracy:", round(accuracy_score(y_test, lr_pred), 4))
print(classification_report(y_test, lr_pred))
 
print("Decision Tree (80:20)")
print("Confusion Matrix:")
print(confusion_matrix(y_test, dt_pred))
print("Accuracy:", round(accuracy_score(y_test, dt_pred), 4))
print(classification_report(y_test, dt_pred))
 
print("Random Forest (80:20)")
print("Confusion Matrix:")
print(confusion_matrix(y_test, rf_pred))
print("Accuracy:", round(accuracy_score(y_test, rf_pred), 4))
print(classification_report(y_test, rf_pred))
 
print("Ngan Nguyen - 041154207") 
# Multiple Train/Test Splits
 
# Try 80:20 split
print("\n80:20 Split")
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
lr.fit(X_train, y_train)
dt.fit(X_train, y_train)
rf.fit(X_train, y_train)
print("Logistic Regression:", round(accuracy_score(y_test, lr.predict(X_test)), 4))
print("Decision Tree:      ", round(accuracy_score(y_test, dt.predict(X_test)), 4))
print("Random Forest:      ", round(accuracy_score(y_test, rf.predict(X_test)), 4))
 
# Try 70:30 split
print("\n70:30 Split")
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
lr.fit(X_train, y_train)
dt.fit(X_train, y_train)
rf.fit(X_train, y_train)
print("Logistic Regression:", round(accuracy_score(y_test, lr.predict(X_test)), 4))
print("Decision Tree:      ", round(accuracy_score(y_test, dt.predict(X_test)), 4))
print("Random Forest:      ", round(accuracy_score(y_test, rf.predict(X_test)), 4))
 
# Try 85:15 split
print("\n85:15 Split")
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.15, random_state=42)
lr.fit(X_train, y_train)
dt.fit(X_train, y_train)
rf.fit(X_train, y_train)
print("Logistic Regression:", round(accuracy_score(y_test, lr.predict(X_test)), 4))
print("Decision Tree:      ", round(accuracy_score(y_test, dt.predict(X_test)), 4))
print("Random Forest:      ", round(accuracy_score(y_test, rf.predict(X_test)), 4))

Ngan Nguyen - 041154207
Logistic Regression (80:20)
Confusion Matrix:
[[90 15]
 [19 55]]
Accuracy: 0.8101
              precision    recall  f1-score   support

           0       0.83      0.86      0.84       105
           1       0.79      0.74      0.76        74

    accuracy                           0.81       179
   macro avg       0.81      0.80      0.80       179
weighted avg       0.81      0.81      0.81       179

Decision Tree (80:20)
Confusion Matrix:
[[84 21]
 [18 56]]
Accuracy: 0.7821
              precision    recall  f1-score   support

           0       0.82      0.80      0.81       105
           1       0.73      0.76      0.74        74

    accuracy                           0.78       179
   macro avg       0.78      0.78      0.78       179
weighted avg       0.78      0.78      0.78       179

Random Forest (80:20)
Confusion Matrix:
[[91 14]
 [18 56]]
Accuracy: 0.8212
              precision    recall  f1-score   support

           0       0.83      0.87      0.85       105
           1       0.80      0.76      0.78        74

    accuracy                           0.82       179
   macro avg       0.82      0.81      0.81       179
weighted avg       0.82      0.82      0.82       179

Ngan Nguyen - 041154207

80:20 Split
Logistic Regression: 0.8101
Decision Tree:       0.7821
Random Forest:       0.8212

70:30 Split
Logistic Regression: 0.8097
Decision Tree:       0.7463
Random Forest:       0.7799

85:15 Split
Logistic Regression: 0.8134
Decision Tree:       0.7761
Random Forest:       0.8433

In [73]:
print("Ngan Nguyen - 041154207")
print("\nConclusion: Random Forest with 85:15 split has the best performance because it has the highest accuracy value.")

Ngan Nguyen - 041154207

Conclusion: Random Forest with 85:15 split has the best performance because it has the highest accuracy value.

### 6. Explain and tune Hyperparameters (n_estimators, max_depth, max_features)

In [88]:
print("Ngan Nguyen - 041154207")

Ngan Nguyen - 041154207

### Hyperparameter Tuning in Random Forest

Hyperparameter tuning is the process of adjusting model configuration settings before training in order to improve prediction performance.

In this task, three important Random Forest hyperparameters are tuned:

**1. n_estimators**  
This parameter defines the number of decision trees in the forest.  
Increasing the number of trees generally improves model stability and accuracy, but also increases computational cost.

**2. max_depth**  
This parameter controls the maximum depth of each decision tree.  
A larger depth allows the model to learn more complex patterns but may lead to overfitting.  
A smaller depth makes the model simpler and may reduce overfitting.

**3. max_features**  
This parameter specifies the number of features considered when looking for the best split.  
Using fewer features increases randomness and can improve generalization performance.

By tuning these hyperparameters, we aim to find the combination that provides the best prediction accuracy on the test dataset.

In [87]:
print("Ngan Nguyen - 041154207\n")

# Values to try for each hyperparameter
n_estimators_list = [50, 100, 200]
max_depth_list = [3, 5, 10]
max_features_list = ['sqrt', 'log2']
 
# Print table header
print(f"{'n_estimators':<15} {'max_depth':<12} {'max_features':<15} {'Accuracy':<10}")
print("-" * 52)
 
# Store results to find the best one
best_acc = 0
best_combo = ""
 
# Try every combination
for n in n_estimators_list:
    for d in max_depth_list:
        for f in max_features_list:
            rf = RandomForestClassifier(n_estimators=n, max_depth=d, max_features=f, random_state=42)
            rf.fit(X_train, y_train)
            acc = round(accuracy_score(y_test, rf.predict(X_test)), 4)
            print(f"{n:<15} {d:<12} {f:<15} {acc:<10}")
 
            if acc > best_acc:
                best_acc = acc
                best_combo = f"n_estimators={n}, max_depth={d}, max_features={f}"
 
print("-" * 52)
print(f"\nBest combination: {best_combo}")
print(f"Best accuracy: {best_acc}")

Ngan Nguyen - 041154207

n_estimators    max_depth    max_features    Accuracy
----------------------------------------------------
50              3            sqrt            0.8134
50              3            log2            0.8134
50              5            sqrt            0.8134
50              5            log2            0.8284
50              10           sqrt            0.8433
50              10           log2            0.8358
100             3            sqrt            0.8284
100             3            log2            0.806
100             5            sqrt            0.8134
100             5            log2            0.8358
100             10           sqrt            0.8358
100             10           log2            0.8358
200             3            sqrt            0.8209
200             3            log2            0.8134
200             5            sqrt            0.8134
200             5            log2            0.8358
200             10           sqrt            0.8284
200             10           log2            0.8358
----------------------------------------------------

Best combination: n_estimators=50, max_depth=10, max_features=sqrt
Best accuracy: 0.8433

#### 7. Use cross validation to evaluate the model (kfold=5).

* KFold → defines how dataset is split into folds
* cross_val_score → automatically trains & tests model on each fold
* n_splits=5 → dataset divided into 5 parts --> Model will train 5 times. Each time → different fold is used as test set
* shuffle=True → randomize data before splitting
* random_state=42 → ensures reproducible splits

In [89]:
from sklearn.model_selection import cross_val_score, KFold

print("Ngan Nguyen - 041154207")

#Defines dataset to split into 5 folds
kf = KFold(n_splits=5, shuffle=True, random_state=42)

# Define machine learning models to evaluate
models = {
    "Logistic Regression": LogisticRegression(max_iter=1000, random_state=42),  
    "Decision Tree": DecisionTreeClassifier(random_state=42),                  
    "Random Forest": RandomForestClassifier(random_state=42)                  
}
# Create empty list to store cross validation results
results = []

# loop through each model
for name, model in models.items():
    # perform 5-fold cross validation using accuracy as evaluation metric
    scores = cross_val_score(model, X, y, cv=kf, scoring='accuracy')
    # store model name, mean accuracy, standard deviation, and fold accuracies
    results.append([name,round(scores.mean(), 4), round(scores.std(), 4),[round(s, 4) for s in scores]])

# Convert results list into structured table (DataFrame)
cv_results = pd.DataFrame(results, columns=["Model", "Mean Accuracy", "Std Dev", "Fold Accuracies"])

# Display final comparison table
cv_results

Ngan Nguyen - 041154207

,Model,Mean Accuracy,Std Dev,Fold Accuracies
0,Logistic Regression,0.8036,0.0220,"[0.8101, 0.7978, 0.8427, 0.7809, 0.7865]"
1,Decision Tree,0.7766,0.0190,"[0.7821, 0.764, 0.809, 0.7528, 0.7753]"
2,Random Forest,0.8148,0.0221,"[0.8101, 0.7809, 0.8483, 0.809, 0.8258]"